/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVencimientosRouteImport } from './routes/_authenticated/vencimientos'
import { Route as AuthenticatedTarjetasRouteImport } from './routes/_authenticated/tarjetas'
import { Route as AuthenticatedProyeccionesRouteImport } from './routes/_authenticated/proyecciones'
import { Route as AuthenticatedPrestamoRouteImport } from './routes/_authenticated/prestamo'
import { Route as AuthenticatedPatrimonioRouteImport } from './routes/_authenticated/patrimonio'
import { Route as AuthenticatedMovimientosRouteImport } from './routes/_authenticated/movimientos'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedInversionesRouteImport } from './routes/_authenticated/inversiones'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedInmueblesRouteImport } from './routes/_authenticated/inmuebles'
import { Route as AuthenticatedIngresosRouteImport } from './routes/_authenticated/ingresos'
import { Route as AuthenticatedGastosFijosRouteImport } from './routes/_authenticated/gastos-fijos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedCalendarioFinancieroRouteImport } from './routes/_authenticated/calendario-financiero'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVencimientosRoute =
  AuthenticatedVencimientosRouteImport.update({
    id: '/vencimientos',
    path: '/vencimientos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarjetasRoute = AuthenticatedTarjetasRouteImport.update({
  id: '/tarjetas',
  path: '/tarjetas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProyeccionesRoute =
  AuthenticatedProyeccionesRouteImport.update({
    id: '/proyecciones',
    path: '/proyecciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrestamoRoute = AuthenticatedPrestamoRouteImport.update({
  id: '/prestamo',
  path: '/prestamo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatrimonioRoute = AuthenticatedPatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimientosRoute =
  AuthenticatedMovimientosRouteImport.update({
    id: '/movimientos',
    path: '/movimientos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInversionesRoute =
  AuthenticatedInversionesRouteImport.update({
    id: '/inversiones',
    path: '/inversiones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInmueblesRoute = AuthenticatedInmueblesRouteImport.update({
  id: '/inmuebles',
  path: '/inmuebles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIngresosRoute = AuthenticatedIngresosRouteImport.update({
  id: '/ingresos',
  path: '/ingresos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGastosFijosRoute =
  AuthenticatedGastosFijosRouteImport.update({
    id: '/gastos-fijos',
    path: '/gastos-fijos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarioFinancieroRoute =
  AuthenticatedCalendarioFinancieroRouteImport.update({
    id: '/calendario-financiero',
    path: '/calendario-financiero',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/calendario-financiero': typeof AuthenticatedCalendarioFinancieroRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gastos-fijos': typeof AuthenticatedGastosFijosRoute
  '/ingresos': typeof AuthenticatedIngresosRoute
  '/inmuebles': typeof AuthenticatedInmueblesRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/inversiones': typeof AuthenticatedInversionesRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/movimientos': typeof AuthenticatedMovimientosRoute
  '/patrimonio': typeof AuthenticatedPatrimonioRoute
  '/prestamo': typeof AuthenticatedPrestamoRoute
  '/proyecciones': typeof AuthenticatedProyeccionesRoute
  '/tarjetas': typeof AuthenticatedTarjetasRoute
  '/vencimientos': typeof AuthenticatedVencimientosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/calendario-financiero': typeof AuthenticatedCalendarioFinancieroRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gastos-fijos': typeof AuthenticatedGastosFijosRoute
  '/ingresos': typeof AuthenticatedIngresosRoute
  '/inmuebles': typeof AuthenticatedInmueblesRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/inversiones': typeof AuthenticatedInversionesRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/movimientos': typeof AuthenticatedMovimientosRoute
  '/patrimonio': typeof AuthenticatedPatrimonioRoute
  '/prestamo': typeof AuthenticatedPrestamoRoute
  '/proyecciones': typeof AuthenticatedProyeccionesRoute
  '/tarjetas': typeof AuthenticatedTarjetasRoute
  '/vencimientos': typeof AuthenticatedVencimientosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/calendario-financiero': typeof AuthenticatedCalendarioFinancieroRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gastos-fijos': typeof AuthenticatedGastosFijosRoute
  '/_authenticated/ingresos': typeof AuthenticatedIngresosRoute
  '/_authenticated/inmuebles': typeof AuthenticatedInmueblesRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/inversiones': typeof AuthenticatedInversionesRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/movimientos': typeof AuthenticatedMovimientosRoute
  '/_authenticated/patrimonio': typeof AuthenticatedPatrimonioRoute
  '/_authenticated/prestamo': typeof AuthenticatedPrestamoRoute
  '/_authenticated/proyecciones': typeof AuthenticatedProyeccionesRoute
  '/_authenticated/tarjetas': typeof AuthenticatedTarjetasRoute
  '/_authenticated/vencimientos': typeof AuthenticatedVencimientosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alertas'
    | '/calendario-financiero'
    | '/configuracion'
    | '/dashboard'
    | '/gastos-fijos'
    | '/ingresos'
    | '/inmuebles'
    | '/insights'
    | '/inversiones'
    | '/metas'
    | '/movimientos'
    | '/patrimonio'
    | '/prestamo'
    | '/proyecciones'
    | '/tarjetas'
    | '/vencimientos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alertas'
    | '/calendario-financiero'
    | '/configuracion'
    | '/dashboard'
    | '/gastos-fijos'
    | '/ingresos'
    | '/inmuebles'
    | '/insights'
    | '/inversiones'
    | '/metas'
    | '/movimientos'
    | '/patrimonio'
    | '/prestamo'
    | '/proyecciones'
    | '/tarjetas'
    | '/vencimientos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/alertas'
    | '/_authenticated/calendario-financiero'
    | '/_authenticated/configuracion'
    | '/_authenticated/dashboard'
    | '/_authenticated/gastos-fijos'
    | '/_authenticated/ingresos'
    | '/_authenticated/inmuebles'
    | '/_authenticated/insights'
    | '/_authenticated/inversiones'
    | '/_authenticated/metas'
    | '/_authenticated/movimientos'
    | '/_authenticated/patrimonio'
    | '/_authenticated/prestamo'
    | '/_authenticated/proyecciones'
    | '/_authenticated/tarjetas'
    | '/_authenticated/vencimientos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vencimientos': {
      id: '/_authenticated/vencimientos'
      path: '/vencimientos'
      fullPath: '/vencimientos'
      preLoaderRoute: typeof AuthenticatedVencimientosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarjetas': {
      id: '/_authenticated/tarjetas'
      path: '/tarjetas'
      fullPath: '/tarjetas'
      preLoaderRoute: typeof AuthenticatedTarjetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyecciones': {
      id: '/_authenticated/proyecciones'
      path: '/proyecciones'
      fullPath: '/proyecciones'
      preLoaderRoute: typeof AuthenticatedProyeccionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prestamo': {
      id: '/_authenticated/prestamo'
      path: '/prestamo'
      fullPath: '/prestamo'
      preLoaderRoute: typeof AuthenticatedPrestamoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patrimonio': {
      id: '/_authenticated/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof AuthenticatedPatrimonioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimientos': {
      id: '/_authenticated/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof AuthenticatedMovimientosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inversiones': {
      id: '/_authenticated/inversiones'
      path: '/inversiones'
      fullPath: '/inversiones'
      preLoaderRoute: typeof AuthenticatedInversionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inmuebles': {
      id: '/_authenticated/inmuebles'
      path: '/inmuebles'
      fullPath: '/inmuebles'
      preLoaderRoute: typeof AuthenticatedInmueblesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ingresos': {
      id: '/_authenticated/ingresos'
      path: '/ingresos'
      fullPath: '/ingresos'
      preLoaderRoute: typeof AuthenticatedIngresosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gastos-fijos': {
      id: '/_authenticated/gastos-fijos'
      path: '/gastos-fijos'
      fullPath: '/gastos-fijos'
      preLoaderRoute: typeof AuthenticatedGastosFijosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario-financiero': {
      id: '/_authenticated/calendario-financiero'
      path: '/calendario-financiero'
      fullPath: '/calendario-financiero'
      preLoaderRoute: typeof AuthenticatedCalendarioFinancieroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedCalendarioFinancieroRoute: typeof AuthenticatedCalendarioFinancieroRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGastosFijosRoute: typeof AuthenticatedGastosFijosRoute
  AuthenticatedIngresosRoute: typeof AuthenticatedIngresosRoute
  AuthenticatedInmueblesRoute: typeof AuthenticatedInmueblesRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedInversionesRoute: typeof AuthenticatedInversionesRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedMovimientosRoute: typeof AuthenticatedMovimientosRoute
  AuthenticatedPatrimonioRoute: typeof AuthenticatedPatrimonioRoute
  AuthenticatedPrestamoRoute: typeof AuthenticatedPrestamoRoute
  AuthenticatedProyeccionesRoute: typeof AuthenticatedProyeccionesRoute
  AuthenticatedTarjetasRoute: typeof AuthenticatedTarjetasRoute
  AuthenticatedVencimientosRoute: typeof AuthenticatedVencimientosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedCalendarioFinancieroRoute:
    AuthenticatedCalendarioFinancieroRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGastosFijosRoute: AuthenticatedGastosFijosRoute,
  AuthenticatedIngresosRoute: AuthenticatedIngresosRoute,
  AuthenticatedInmueblesRoute: AuthenticatedInmueblesRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedInversionesRoute: AuthenticatedInversionesRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedMovimientosRoute: AuthenticatedMovimientosRoute,
  AuthenticatedPatrimonioRoute: AuthenticatedPatrimonioRoute,
  AuthenticatedPrestamoRoute: AuthenticatedPrestamoRoute,
  AuthenticatedProyeccionesRoute: AuthenticatedProyeccionesRoute,
  AuthenticatedTarjetasRoute: AuthenticatedTarjetasRoute,
  AuthenticatedVencimientosRoute: AuthenticatedVencimientosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
